trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '**/Dockerfile'
        tags: |
          $(tag)

    - script: docker images
      displayName: List Docker images

    - task: Docker@2
      displayName: Save Docker image as artifact
      inputs:
        command: save
        imageName: 'coronavirus-tracker:$(tag)'
        includeLayers: true
        outputPath: '$(Build.ArtifactStagingDirectory)/coronavirus-tracker.tar'

    - task: PublishBuildArtifacts@1
      displayName: Publish Docker image artifact
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'coronavirus-tracker-image'
        publishLocation: 'Container'
