trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: AzureCLI@2
  inputs:
    azureSubscription: 'Azure Subscription 1(7f64bf91-2d58-4a80-ae8e-da09dee3825d)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      docker build -t testingacr001.azurecr.io/coronavirus-tracker:tag .
      az acr login -n testingacr001
      docker push testingacr001.azurecr.io/coronavirus-tracker:tag

