apiVersion : apps/v1
kind: Deployment
metadata:
  name: sampleapp
spec:
  replicas: #replicaNo#
  selector:
    matchLabels:
      app: sampleapp
  template:
    metadata:
      labels:
        app: sampleapp 
    spec:
      containers:
        - name: sampleapp 
          image: testingacr001.azurecr.io/sampleapp
          ports:
          - containerPort: 80
          - containerPort: 443