apiVersion: v1
kind: Service
metadata:
    name: sampleapp
spec:
    type: LoadBalancer
    ports:
      - protocol: TCP
        port: 80
        targetPort: 3000 
    selector:
        app: sampleapp