apiVersion: v1
kind: Service
metadata:
    name: sampleapp
spec:
    type: LoadBalancer
    ports:
      - protocol: TCP
        port: 80
        targetPort: 80
      - protocol: TCP
        port: 443
        targetPort: 443
    selector:
        app: sampleapp