apiVersion: v1
kind: Service
metadata:
    name: sampleapp-prod-service
    labels:
        app: sampleapp
        environment: prod
spec:
    type: LoadBalancer
    ports:
    - port: 80 
    selector:
        app: sampleapp
        environment: prod