apiVersion: v1
kind: Service
metadata:
    name: sampleapp
spec:
    type: LoadBalancer
    ports:
      - targetPort: 80
        name: port80
        port: 80
        protocol: TCP
      - targetPort: 443
        name: port443
        port: 443
        protocol: TCP
    selector:
        app: sampleapp