apiVersion: v1
kind: Service
metadata:
    name: sampleapp-prod-service
    labels:
        app: sampleapp
        environment: prod
spec:
    type: LoadBalancer
    ports:
      - protocol: TCP
        port: 80
        targetPort: 3000
    selector:
        app: sampleapp
        environment: prod